### ISSUE TITLE
Client and server ESNI key selection

### ISSUE THREAD

**Issue by chris-wood** [ekr/draft-rescorla-tls-esni#27]
Doing so doesn't allow a server to gracefully generate new ESNI keys and retire old ones. We should mandate that clients always choose the first ESNI key for which they have group support. If we adopt #24, where servers lookup keys with a (label, group) -> key mapping, should we also require that each label have the same groups?

**Comment by chris-wood** [comment]
@kazuho what do you think?

**Comment by kazuho** [comment]
I am not sure what you mean by "doing so", but the model I expect is something like following assuming that we adopt #24.

* the fronting server generates a new ESNIKeys and pushes it to DNS server every 1 hour
  * TTL will be set to `not_after` - now
* the fronting server will accept the following keys to be used in the EncryptedSNI extension:
  * the key for the current hour
  * the key for the previous hour, for the first few minutes of every hour

A ESNIKeys record can contain multiple keys belonging to different groups, but not belonging to the same group. So there is no ambiguity by specifying the key using (label, group).

The server can add a new Named Group or retire one when it generates a new ESNIKeys.

**Comment by chris-wood** [comment]
That seems perfectly fine. But it does mean that there exists only one key per group at any given point in time. Is that a restriction we are comfortable with?

**Comment by kazuho** [comment]
I am comfortable with not having that. You can only have a handful of keys in ESNIKeys anyways.

I'd assume that either one would be enough or we would need a way to distribute more than just a handful, for which we can use round-robin.

**Comment by chris-wood** [comment]
SGTM. We should add this rationale as text to the DNS record section.

**Comment by martinthomson** [comment]
I think that TTL suffices here.

**Comment by kazuho** [comment]
@martinthomson FWIW, `not_after` is now in master. We can certainly discuss about the necessity, but you might want to see the debate on #23.

**Comment by ghedo** [comment]
@kazuho I think your point in the PR is quite valid. However it's probably worth noting that having explicit not_before / not_after that the client has to validate, is likely to make it very difficult, if not impossible, to deploy very-short-lived keys (say, in the order of a few hours), due to the fact that a significant portion of clients have shitty clocks (https://ai.google/research/pubs/pub46359), which affects forward secrecy.

Maybe it should be noted in the spec as an appendix or something.

**Comment by ghedo** [comment]
Hmmm, thinking about this some more. In the "split brain" case @kazuho described in #23, the not_after is used to avoid having clients send an ESNI encrypted with an old key (as fetched from an out-of-date DNS server), to a TLS server that might have already switched to a new key (thus causing the connection to break).

So i'm guessing what happens is that the client would fallback to plaintext SNI if the key it fetched from DNS is expired. Though it seems to me this fallback could be dangerous for the client since they would end up exposing the SNI, but I can't come up with a practical way to exploit this (could be dependent on the specific deployment I guess).

Whether this is something worth fixing is a different question, but an alternative to fix the split brain problem would be for the TLS server to somehow make sure the new key has been received by the DNS server, before discarding the old one.

Did I understand the problem you described in #23 correctly @kazuho ?

**Comment by kazuho** [comment]
@ghedo Thank you for your comments.

> I think your point in the PR is quite valid. However it's probably worth noting that having explicit not_before / not_after that the client has to validate, is likely to make it very difficult, if not impossible, to deploy very-short-lived keys (say, in the order of a few hours), due to the fact that a significant portion of clients have shitty clocks (https://ai.google/research/pubs/pub46359), which affects forward secrecy.

I think you are correct in stating that the ESNIKeys cannot have a very short lifetime. However, I would like to argue that the fact does not prevent server operators from rotating the keys frequently.

Server operators can rotate the keys at the speed they like, as well as retiring them from the servers in any way.

> So i'm guessing what happens is that the client would fallback to plaintext SNI if the key it fetched from DNS is expired. Though it seems to me this fallback could be dangerous for the client since they would end up exposing the SNI, but I can't come up with a practical way to exploit this (could be dependent on the specific deployment I guess).

I agree with what happens.

In my view, ESNI is opportunistic encryption in sense that the unencrypted hostname is used when the ESNI resource record fails to reach the client (including the case of a middlebox dropping it intentionally).

I would argue that using SNI in case of receiving an expired ESNI record is one of the failure modes in distributing the correct resource record. And therefore, I do not think that it is a security concern.

> Whether this is something worth fixing is a different question, but an alternative to fix the split brain problem would be for the TLS server to somehow make sure the new key has been received by the DNS server, before discarding the old one.

That is correct. However, I fear that having such a requirement hinders us from using existing DNS deployments, because DNS authoritative servers are designed to favor availability over consistency, whereas in our case without `not_after`, we need consistency over availability.

**Comment by ghedo** [comment]
> Server operators can rotate the keys at the speed they like, as well as retiring them from the servers in any way.

I didn't realize that was possible (that is, I kind of assumed servers would have to keep the key around until the not_after expired, but it's not actually written anywhere). In that case fine, though it might be worth clarifying.

The other concern I had was risking of turning this into another OCSP (where network failure and attack basically look the same so clients end up ignoring both), but I guess that with DoH, DPRIVE and DNSSEC an attack here is much harder to pull off. So all in all I don't have a strong opinion on not_before / not_after anymore.

**Comment by ekr** [comment]
I think this is fine, @chris-wood please re-open if not.
