### ISSUE TITLE
Recast Fronting mode as Split Mode

### ISSUE THREAD

**Issue by chris-wood** [ekr/draft-rescorla-tls-esni#28]
Domain fronting already has a bad rap. Perhaps we should give this a new name to avoid pushback?

**Comment by mcmanus** [comment]
I'm going to go a step farther and suggest only defining shared mode in this document.

it brings esni to the masses and eliminates the need for special tech to acheive classic fronting. That's a significant net-win without being weighed down by bias about fronting - I think we'll get more participation that way because the set of goals is easier to achieve consensus on (privacy is good!)

If folks need a separate document later to figure out they can tunnel based on the decrypted SNI then istm it can be separable.. true?

**Comment by chris-wood** [comment]
@mcmanus My reservation there is that, with only Shared Mode, a better design is probably to encrypt all of the extensions, and not just the SNI. With that change, it then later becomes infeasible to accomplish the front/hidden split.

**Comment by chris-wood** [comment]
Closing via #45. @mcmanus if we want to keep only Shared Mode, let's use a new issue to track that.
