### ISSUE TITLE
Reuse RFC 6066 ServerName extension / Do not define a new extension

### ISSUE THREAD

**Issue by kontaxis** [ekr/draft-rescorla-tls-esni#39]
6.2 Middleboxes identifies a legitimate concern where middleboxes might strip a new ESNI extension that is unknown to them.

The ServerName structure as defined in RFC 6066 has an 8-bit NameType field where 0 is defined as host_name and all other values are undefined. Why not define 1 (or any other value) as encrypted_host_name?

The name structure inside ServerName is 16 opaque bits which seems able to accommodate EncryptedSNI as defined in this document. (Make encrypted_sni slightly smaller so that "label" and "suite" fit)

**Comment by kazuho** [comment]
I prefer having a different extension, because we do not want to limit the capability of ESNIKeys to just protecting the "HostName" (as identified by the 8-bit NameType field of zero).  IMO it is better to have a mechanism that can protect any type of "server-name", including those covered by NameTypes other than zero.

Note that DNS is just one way of publishing ESNIKeys.

**Comment by chris-wood** [comment]
I agree with @kazuho.

**Comment by kontaxis** [comment]
I didn't mean for ESNI to only apply to NameType 0.

There are 256 values, 0 is host_name, 1 can be encrypted_server_name, and there are 254 more values for additional types of server name types. Going forward I doubt someone will define a plain text type that will have to be protected. But even if that happens encrypted_server_name can encapsulate all name types but itself.

P.S.: Not really sure how the use of DNS is a factor here.

**Comment by martinthomson** [comment]
Recall that SNI extensibility is [irrevocably busted](https://mailarchive.ietf.org/arch/msg/tls/1t79gzNItZd71DwwoaqcQQ_4Yxc).

**Comment by kontaxis** [comment]
Fair enough.
