### ISSUE TITLE
Versioning for the record?

### ISSUE THREAD

**Issue by ekr** [ekr/draft-rescorla-tls-esni#63]
Do we need it.

**Comment by kazuho** [comment]
For ESNIKeys (the DNS record) I do not think we need a version for the following reasons:
* I think we would prefer adding extensions rather than making incompatible changes
* we always have the freedom to pick a new prefix (e.g. `_esni2`) or a new RR type when making incompatible changes
  * an incompatible change will require the client to query for two DNS records anyways

For the ESNI extension, I also do not think that we need a version field. When we define an extension sometime in the future, we could the advertise the support as an extension in the ESNIKeys to instruct the clients that support that extension to send a CH extension that uses a different extension ID than the ESNI extension.

**Comment by martinthomson** [comment]
> an incompatible change will require the client to query for two DNS records anyways

A lot of other TXT records have a version in them.  It turns out that if you do that you can query for TXT records and get multiple answers back.  Then, you pick those with the version you like.  That's one query.

I'm tempted to suggest that the first octet (or two) be used for a version number.  It's cheap.

**Comment by ekr** [comment]
I'm concerned about how we iterate on these in the field. They're not tied to TLS version, so what if we decide to change the formats, as we are discussing in #67

**Comment by mcmanus** [comment]
a magic number (including version) is a pretty decent idea. right now _esni is in its own namespace but you can imagine someone doing a txt record that applies to every dns response so we would want to disambiguate that as well.

take note to update the "concat multiple records" rule if we go down this path..

**Comment by kazuho** [comment]
I think that having version is a good idea in sense that it allows to do experiments before the standardization completes.
