### ISSUE TITLE
Where do the TXT records go?

### ISSUE THREAD

**Issue by martinthomson** [ekr/draft-rescorla-tls-esni#7]
In DNS, yes, but under what name?  

I suggest at _esni.<domain>.  Usage of TXT and underscore names is now considered an acceptable way to deploy new features.  It also deploys more reliably than a new RRtype.

**Comment by kazuho** [comment]
I would like to note that the use of RRtype would be a no-go for many operators, because you cannot delegate an APEX name.

Many websites are served by their APEX names. It is common for a web-site publisher to choose different hosting providers for HTTP (i.e. CDN) and DNS

These facts lead to the conclusion that if we choose RRtype as the method, there would often be the cases where the DNS record of the ESNIKey and the TLS server would be required to be operated by different entities.

This essentially means that there would be high risk of ESNIKey record and the key in TLS server becoming out-of-sync for large amount of deployments.

Having such _additional_ risk in operation for a nice-to-have feature like ESNI would be unacceptable for many operators.

**Comment by ekr** [comment]
@kazuho: we went with TXT.
